psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER csr WITH PASSWORD 'csr';
    CREATE DATABASE csr;
    GRANT ALL PRIVILEGES ON DATABASE csr TO csr;
EOSQL