// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/activearea"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/predicate"
)

// ActiveAreaDelete is the builder for deleting a ActiveArea entity.
type ActiveAreaDelete struct {
	config
	hooks    []Hook
	mutation *ActiveAreaMutation
}

// Where appends a list predicates to the ActiveAreaDelete builder.
func (aad *ActiveAreaDelete) Where(ps ...predicate.ActiveArea) *ActiveAreaDelete {
	aad.mutation.Where(ps...)
	return aad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aad *ActiveAreaDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aad.hooks) == 0 {
		affected, err = aad.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ActiveAreaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aad.mutation = mutation
			affected, err = aad.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aad.hooks) - 1; i >= 0; i-- {
			if aad.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aad.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aad.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aad *ActiveAreaDelete) ExecX(ctx context.Context) int {
	n, err := aad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aad *ActiveAreaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: activearea.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: activearea.FieldID,
			},
		},
	}
	if ps := aad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, aad.driver, _spec)
}

// ActiveAreaDeleteOne is the builder for deleting a single ActiveArea entity.
type ActiveAreaDeleteOne struct {
	aad *ActiveAreaDelete
}

// Exec executes the deletion query.
func (aado *ActiveAreaDeleteOne) Exec(ctx context.Context) error {
	n, err := aado.aad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{activearea.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aado *ActiveAreaDeleteOne) ExecX(ctx context.Context) {
	aado.aad.ExecX(ctx)
}
