// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/activearea"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/user"
)

// ActiveAreaCreate is the builder for creating a ActiveArea entity.
type ActiveAreaCreate struct {
	config
	mutation *ActiveAreaMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (aac *ActiveAreaCreate) SetName(s string) *ActiveAreaCreate {
	aac.mutation.SetName(s)
	return aac
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (aac *ActiveAreaCreate) AddUserIDs(ids ...int) *ActiveAreaCreate {
	aac.mutation.AddUserIDs(ids...)
	return aac
}

// AddUsers adds the "users" edges to the User entity.
func (aac *ActiveAreaCreate) AddUsers(u ...*User) *ActiveAreaCreate {
	ids := make([]int, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return aac.AddUserIDs(ids...)
}

// Mutation returns the ActiveAreaMutation object of the builder.
func (aac *ActiveAreaCreate) Mutation() *ActiveAreaMutation {
	return aac.mutation
}

// Save creates the ActiveArea in the database.
func (aac *ActiveAreaCreate) Save(ctx context.Context) (*ActiveArea, error) {
	var (
		err  error
		node *ActiveArea
	)
	if len(aac.hooks) == 0 {
		if err = aac.check(); err != nil {
			return nil, err
		}
		node, err = aac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ActiveAreaMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aac.check(); err != nil {
				return nil, err
			}
			aac.mutation = mutation
			if node, err = aac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(aac.hooks) - 1; i >= 0; i-- {
			if aac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (aac *ActiveAreaCreate) SaveX(ctx context.Context) *ActiveArea {
	v, err := aac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aac *ActiveAreaCreate) Exec(ctx context.Context) error {
	_, err := aac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aac *ActiveAreaCreate) ExecX(ctx context.Context) {
	if err := aac.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aac *ActiveAreaCreate) check() error {
	if _, ok := aac.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ActiveArea.name"`)}
	}
	if v, ok := aac.mutation.Name(); ok {
		if err := activearea.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ActiveArea.name": %w`, err)}
		}
	}
	return nil
}

func (aac *ActiveAreaCreate) sqlSave(ctx context.Context) (*ActiveArea, error) {
	_node, _spec := aac.createSpec()
	if err := sqlgraph.CreateNode(ctx, aac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (aac *ActiveAreaCreate) createSpec() (*ActiveArea, *sqlgraph.CreateSpec) {
	var (
		_node = &ActiveArea{config: aac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: activearea.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: activearea.FieldID,
			},
		}
	)
	if value, ok := aac.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: activearea.FieldName,
		})
		_node.Name = value
	}
	if nodes := aac.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activearea.UsersTable,
			Columns: []string{activearea.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActiveAreaCreateBulk is the builder for creating many ActiveArea entities in bulk.
type ActiveAreaCreateBulk struct {
	config
	builders []*ActiveAreaCreate
}

// Save creates the ActiveArea entities in the database.
func (aacb *ActiveAreaCreateBulk) Save(ctx context.Context) ([]*ActiveArea, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aacb.builders))
	nodes := make([]*ActiveArea, len(aacb.builders))
	mutators := make([]Mutator, len(aacb.builders))
	for i := range aacb.builders {
		func(i int, root context.Context) {
			builder := aacb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActiveAreaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aacb *ActiveAreaCreateBulk) SaveX(ctx context.Context) []*ActiveArea {
	v, err := aacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aacb *ActiveAreaCreateBulk) Exec(ctx context.Context) error {
	_, err := aacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aacb *ActiveAreaCreateBulk) ExecX(ctx context.Context) {
	if err := aacb.Exec(ctx); err != nil {
		panic(err)
	}
}
