// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/kind"
)

// Kind is the model entity for the Kind schema.
type Kind struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// MaxReservationTime holds the value of the "max_reservation_time" field.
	MaxReservationTime int64 `json:"max_reservation_time,omitempty"`
	// MaxReservationUnits holds the value of the "max_reservation_units" field.
	MaxReservationUnits int64 `json:"max_reservation_units,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KindQuery when eager-loading is set.
	Edges KindEdges `json:"edges"`
}

// KindEdges holds the relations/edges for other nodes in the graph.
type KindEdges struct {
	// Equipments holds the value of the equipments edge.
	Equipments []*Equipment `json:"equipments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EquipmentsOrErr returns the Equipments value or an error if the edge
// was not loaded in eager-loading.
func (e KindEdges) EquipmentsOrErr() ([]*Equipment, error) {
	if e.loadedTypes[0] {
		return e.Equipments, nil
	}
	return nil, &NotLoadedError{edge: "equipments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Kind) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case kind.FieldID, kind.FieldMaxReservationTime, kind.FieldMaxReservationUnits:
			values[i] = new(sql.NullInt64)
		case kind.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Kind", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Kind fields.
func (k *Kind) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kind.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			k.ID = int(value.Int64)
		case kind.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				k.Name = value.String
			}
		case kind.FieldMaxReservationTime:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_reservation_time", values[i])
			} else if value.Valid {
				k.MaxReservationTime = value.Int64
			}
		case kind.FieldMaxReservationUnits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_reservation_units", values[i])
			} else if value.Valid {
				k.MaxReservationUnits = value.Int64
			}
		}
	}
	return nil
}

// QueryEquipments queries the "equipments" edge of the Kind entity.
func (k *Kind) QueryEquipments() *EquipmentQuery {
	return (&KindClient{config: k.config}).QueryEquipments(k)
}

// Update returns a builder for updating this Kind.
// Note that you need to call Kind.Unwrap() before calling this method if this Kind
// was returned from a transaction, and the transaction was committed or rolled back.
func (k *Kind) Update() *KindUpdateOne {
	return (&KindClient{config: k.config}).UpdateOne(k)
}

// Unwrap unwraps the Kind entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (k *Kind) Unwrap() *Kind {
	tx, ok := k.config.driver.(*txDriver)
	if !ok {
		panic("ent: Kind is not a transactional entity")
	}
	k.config.driver = tx.drv
	return k
}

// String implements the fmt.Stringer.
func (k *Kind) String() string {
	var builder strings.Builder
	builder.WriteString("Kind(")
	builder.WriteString(fmt.Sprintf("id=%v", k.ID))
	builder.WriteString(", name=")
	builder.WriteString(k.Name)
	builder.WriteString(", max_reservation_time=")
	builder.WriteString(fmt.Sprintf("%v", k.MaxReservationTime))
	builder.WriteString(", max_reservation_units=")
	builder.WriteString(fmt.Sprintf("%v", k.MaxReservationUnits))
	builder.WriteByte(')')
	return builder.String()
}

// Kinds is a parsable slice of Kind.
type Kinds []*Kind

func (k Kinds) config(cfg config) {
	for _i := range k {
		k[_i].config = cfg
	}
}
