// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"git.epam.com/epm-lstr/epm-lstr-lc/be/ent/kind"
)

// Kind is the model entity for the Kind schema.
type Kind struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Kind) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case kind.FieldID:
			values[i] = new(sql.NullInt64)
		case kind.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Kind", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Kind fields.
func (k *Kind) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kind.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			k.ID = int(value.Int64)
		case kind.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				k.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Kind.
// Note that you need to call Kind.Unwrap() before calling this method if this Kind
// was returned from a transaction, and the transaction was committed or rolled back.
func (k *Kind) Update() *KindUpdateOne {
	return (&KindClient{config: k.config}).UpdateOne(k)
}

// Unwrap unwraps the Kind entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (k *Kind) Unwrap() *Kind {
	tx, ok := k.config.driver.(*txDriver)
	if !ok {
		panic("ent: Kind is not a transactional entity")
	}
	k.config.driver = tx.drv
	return k
}

// String implements the fmt.Stringer.
func (k *Kind) String() string {
	var builder strings.Builder
	builder.WriteString("Kind(")
	builder.WriteString(fmt.Sprintf("id=%v", k.ID))
	builder.WriteString(", name=")
	builder.WriteString(k.Name)
	builder.WriteByte(')')
	return builder.String()
}

// Kinds is a parsable slice of Kind.
type Kinds []*Kind

func (k Kinds) config(cfg config) {
	for _i := range k {
		k[_i].config = cfg
	}
}
