name: int-test
on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "${{ github.workspace }}/go.mod"
      - name: Cache go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Prepare
        run: |
          make setup
          make generate
      - name: Build image
        run: |
          docker build -t csr:int-test -f ./int-test-infra/Dockerfile.int-test .
      - name: Run service
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./int-test-infra/docker-compose.int-test.yml"
      - name: Test
        run: |
          make int-test-without-infra